/* Retained channel fields share the existing mirror file/state owner. Each
 * native owner and each Property has its own producer-scoped incarnation. */
#ifndef MPC_CHANNEL_STATE_H
#define MPC_CHANNEL_STATE_H
#define CHANNEL_OWNERS 2048u
#define CHANNEL_FIELDS 4096u
#define CHANNEL_HASH 8192u
#define CHANNEL_TEXT 96u
enum {CF_VOLUME,CF_PAN,CF_MUTE,CF_SOLO,CF_ARM,CF_NAME,CF_COLOR,CF_SELECTION,CF_EFFECTIVE_MUTE,CF_SOLO_AUDIO,CF_SEND1,CF_SEND2,CF_SEND3,CF_SEND4,CF_MASTER,CF_PLAYING,CF_AUTOMATION,CF_LOOP,CF_RECORD_MODE,CF_CLICK,CF_MIDI_VOLUME,CF_COUNT};
/* Native routing field tags are separate from command operation numbers.
 * CF_COUNT remains unchanged, preserving every existing musical operation. */
enum {CI_MIDI_MONITOR=CF_COUNT,CI_MIDI_MONITOR_AUDIO,CI_MIDI_IN_PORT,CI_MIDI_IN_CHANNEL,CI_MIDI_OUT_PORT,CI_MIDI_OUT_CHANNEL,CI_SEND_TO,CI_SEND_TO_AUDIO,CI_AUDIO_OUT,CI_AUDIO_OUT_AUDIO,CI_AUDIO_MONITOR,CI_AUDIO_IN,CI_AUDIO_IN_AUDIO,CHANNEL_FIELD_KINDS};
enum {CO_PROGRAM=1,CO_TRACK,CO_PROJECT,CO_MIXER,CO_TIMELINE,CO_AUTOMATION,CO_LOOP,CO_RECORDING,CO_CLICK,CO_EDITOR,CO_ZOOM};
enum {CH_OK,CH_CAPACITY,CH_OWNER,CH_LIFETIME,CH_TEXT,CH_WRAP};
/* CH_CAPACITY records that some birth could not be satisfied. It describes the
 * cells that are absent, never the cells that did register with their own
 * identity, so it does not invalidate a resolving cell. It is therefore never
 * cleared: an exhaustion stays readable in channel.errors for the rest of the
 * session instead of being wiped by the next successful birth of that tag.
 * CH_OWNER/CH_LIFETIME/CH_TEXT/CH_WRAP are correctness faults and still are. */
static inline int channel_fault(unsigned why){return why&&why!=CH_CAPACITY;}
/* An owner incarnation is the lifetime token and carries its own slot in the
 * low bits, so an owner slot can be reused without handing a new lifetime the
 * old lifetime's token, while every consumer still resolves the slot from the
 * token alone. CHANNEL_OWNERS is 2048, so 12 bits hold every slot id. */
#define CHANNEL_OWNER_SLOT_BITS 12u
#define CHANNEL_OWNER_GENERATION_MAX ((1u<<(32-CHANNEL_OWNER_SLOT_BITS))-1u)
static inline unsigned channel_owner_slot(unsigned token){unsigned n=token&((1u<<CHANNEL_OWNER_SLOT_BITS)-1u);return n&&n<=CHANNEL_OWNERS?n:0;}
enum {CH_PROGRAM_BIRTH=47,CH_PROGRAM_COPY,CH_PROGRAM_DEATH,CH_TRACK_BIRTH,
 CH_PAN_BIRTH,CH_PAN_COPY,CH_NAME_BIRTH,CH_COLOR_BIRTH,CH_ARM_BIRTH,
 CH_SELECTION_BIRTH,CH_SELECTION_COMMIT,CH_PROJECT_BIRTH,
 CH_MUTE_BIRTH,CH_MUTE_COPY,CH_SOLO_BIRTH,CH_SOLO_COPY,
 CH_SOLO_AUDIO_BIRTH,CH_SOLO_AUDIO_COPY,CH_EFFECTIVE_BIRTH,CH_EFFECTIVE_COPY,
 CH_BOOL_COMMIT,CH_SEND_BIRTH,CH_SEND_COPY,CH_MIXER_BIRTH,CH_MASTER_BIRTH,CH_MIXER_DEATH,CH_TIMELINE_BIRTH,CH_PLAYING_BIRTH,CH_TIMELINE_DEATH,CH_POSITION_ENTER,CH_POSITION_EXIT,CH_AUTOMATION_OWNER,CH_AUTOMATION_BIRTH,CH_ENUM_COMMIT,CH_LOOP_OWNER,CH_LOOP_BIRTH};
enum {CH_RECORD_OWNER=95,CH_RECORD_BIRTH,CH_RECORD_COMMIT,CH_RECORD_DEATH};
enum {GL_CLICK_OWNER=113,GL_CLICK_BIRTH,GL_CLICK_DEATH,GL_CLICK_DELETE,GL_AUTO_FANOUT,GL_AUTO_STATE,GL_AUTO_EMPTY,GL_AUTO_DEATH,GL_AUTO_DELETE,GL_AUTO_REGISTER,GL_AUTO_UNREGISTER,GL_AUTO_CLEAR,GL_AUTO_ENTER,GL_AUTO_CALLBACK,GL_EDITOR_PUBLISH,GL_EDITOR_DEATH};
enum {IO_IN_PORT_BIRTH=211,IO_IN_CHANNEL_BIRTH,IO_OUT_PORT_BIRTH,IO_OUT_CHANNEL_BIRTH,IO_IN_PORT_COMMIT,IO_OUT_PORT_COMMIT,IO_CHANNEL_COMMIT};
enum {IO_PC_BIRTH=279,IO_PC_DEATH,IO_PC_DELETE,IO_PC_BIND,IO_PC_BOUND,IO_STRING_CATALOGUE,IO_PC_EMPTY,IO_AC_EMPTY,IO_AC_BIND,IO_AC_BOUND,IO_AC_DEATH,IO_AC_DELETE,IO_AC_BIRTH};
enum {IO_AUDIO_IN_COPY=260,IO_OUTPUT_BIRTH0,IO_OUTPUT_BIRTH1,IO_OUTPUT_BIRTH2,IO_OUTPUT_COPY0,IO_OUTPUT_COPY1,IO_OUTPUT_COPY2,IO_OUTPUT_APPLY_BIRTH0,IO_OUTPUT_APPLY_BIRTH1,IO_OUTPUT_APPLY_BIRTH2,IO_OUTPUT_APPLY_COPY0,IO_OUTPUT_APPLY_COPY1,IO_OUTPUT_APPLY_COPY2,IO_OUTPUT_COMMIT0,IO_OUTPUT_COMMIT1,IO_OUTPUT_COMMIT2,IO_OUTPUT_APPLY_COMMIT0,IO_OUTPUT_APPLY_COMMIT1,IO_OUTPUT_APPLY_COMMIT2};
enum {IO_AUDIO_MONITOR_BIRTH=252,IO_AUDIO_MONITOR_COPY,IO_AUDIO_IN_BIRTH,IO_AUDIO_APPLY_BIRTH,IO_AUDIO_APPLY_COPY,IO_AUDIO_UI_COMMIT,IO_AUDIO_MONITOR_COMMIT,IO_AUDIO_APPLY_COMMIT};
enum {IO_DEST_BIRTH=247,IO_DEST_DEATH,IO_DEST_DELETE,IO_DEST_REBUILD,IO_DEST_READY};
enum {IO_MONITOR_BIRTH=233,IO_MONITOR_COMMIT,IO_MONITOR_AUDIO,IO_MONITOR_PREPARE,IO_MONITOR_RESULT,IO_MONITOR_ENTER,IO_MONITOR_DONE,IO_SEND_BIRTH,IO_SEND_COMMIT,IO_SEND_AUDIO,IO_SEND_PREPARE,IO_SEND_RESULT,IO_SEND_ENTER,IO_SEND_DONE};
enum {MI_VOLUME_BIRTH=151,MI_VOLUME_COPY,MI_ENTER,MI_DONE,MI_AUTO_ENTER,MI_AUTO_DONE,MI_SET};
typedef struct {_Atomic uint32_t address,kind,live,incarnation;} ChannelOwner;
typedef struct {
 _Atomic uint32_t property,owner,owner_incarnation,incarnation,field,revision,live,bits,updates,seed,length;
 _Atomic uint32_t text[CHANNEL_TEXT/4];
} ChannelCell;
typedef struct {
 _Atomic uint32_t owner_token,owners_used,fields_used,project_owner,mixer_owner,timeline_owner,automation_owner,loop_owner,record_owner,click_owner,errors[CHANNEL_FIELD_KINDS];
 _Atomic uint32_t owner_directory[CHANNEL_HASH],field_directory[CHANNEL_HASH];
 ChannelOwner owners[CHANNEL_OWNERS];ChannelCell fields[CHANNEL_FIELDS];
} ChannelState;
static inline unsigned channel_offset(unsigned field){
 static const unsigned offsets[CF_COUNT]={0x5b0,0x3d0,0x50,0x88,0x474,0x440,0x5f0,0x78,0x184,0x98,0x428,0x460,0x498,0x4d0,0xa8,0xec,0xc,0x68,0x500,0xc,0x28c};return field<CF_COUNT?offsets[field]:0;
}
static inline unsigned channel_kind(unsigned field){if(field>=CI_MIDI_MONITOR&&field<CHANNEL_FIELD_KINDS)return field<=CI_SEND_TO_AUDIO?CO_TRACK:CO_PROGRAM;return field==CF_CLICK?CO_CLICK:field==CF_RECORD_MODE?CO_RECORDING:field==CF_LOOP?CO_LOOP:field==CF_AUTOMATION?CO_AUTOMATION:field==CF_MASTER?CO_MIXER:field==CF_PLAYING?CO_TIMELINE:field==CF_SELECTION?CO_PROJECT:field==CF_ARM||field==CF_NAME||field==CF_COLOR||field==CF_MIDI_VOLUME?CO_TRACK:CO_PROGRAM;}
#endif
