/* Exact-build finite rooted-model mode. No MPC command API or actuator input. */
#ifndef MPC_MODEL_H
#define MPC_MODEL_H
#define MODEL_TRACKS 128u
#define MODEL_FIELDS 8u
#define MODEL_INVOCATIONS 32u
#define MODEL_INVOCATION_DEPTH 8u
#define MODEL_RETIRED 256u
#define MODEL_LIFE_FILTER ((MODEL_TRACKS+MODEL_RETIRED)*7u)
/* Hook IDs are also emitted as execution-context data. */
enum {
 M_RESET,M_LOAD_ENTER,M_LOAD_RETURN,M_LOAD_READY,M_PROJECT_CLEAR,M_POOL_DESTROY,
 M_ADD_ENTER,M_ADD_COMMIT,M_ADD_EXIT,M_APPEND_ENTER,M_APPEND_COMMIT,M_APPEND_EXIT,
 M_REMOVE_ENTER,M_REMOVE_COMMIT,M_REMOVE_EXIT,M_REORDER_ENTER,M_REORDER_COMMIT,M_REORDER_EXIT,
 M_PROGRAM_ENTER,M_PROGRAM_COMMIT,M_PROGRAM_EXIT,M_POOL_CLEAR,
 M_FLOAT,M_MUTE,M_BOOL,M_COLOR,M_NAME,
 M_ROOT_DESTROY,M_PROJECT_DESTROY,M_TRACK_DESTROY,
 M_RELEASE_ENTER,M_RELEASE_COUNT,M_RETAIN_INCREMENT,M_RETAIN_DECREMENT,
 M_REPLACE_SIMPLE_PRE,M_REPLACE_FULL_PRE,M_REPLACE_SIMPLE_STORE,M_REPLACE_FULL_STORE,M_REPLACE_NOTIFY,
 M_QUEUE_ENTER,M_COMMAND_BODY,M_QUEUE_DONE,M_DIRECT_ENTER,
 M_SITE_COUNT
};
#define PATCH_COUNT M_SITE_COUNT
#define MODEL_HOOK_BASE 100u
/* Appended command-mode source IDs; preserve every existing hook number. */
#define M_CREATE_ENTER 294u
#define M_CREATE_READY 295u
/* Peer libinput pointer-device join; command mode only. */
#define M_POINTER_DEVICE 296u
/* Peer libinput scroll handler, after the wheel delta is stored; command only. */
#define M_WHEEL_DATA 297u
/* Ends of the peer's libinput drain loops, where the banked wheel notches are
 * delivered as one native call; command mode only. Four anchors share one hook
 * body. model-prepare.py derives a site's hook id from its position in the
 * recipe list, so these take consecutive ids rather than one repeated id. */
#define M_WHEEL_FLUSH 298u
#define M_WHEEL_FLUSH_LAST 301u
#define MODEL_FINITE_CLOSE 200u
enum {MODEL_CONTEXT=32,MODEL_STACK,MODEL_ROOT,MODEL_INVALIDATE,MODEL_LOAD,
 MODEL_SNAPSHOT,MODEL_TRACK,MODEL_PROGRAM,MODEL_SCALARS,MODEL_FLAGS,MODEL_NAME,
 MODEL_NAME_END,MODEL_SNAPSHOT_END,MODEL_FIELD,MODEL_FIELD_END,MODEL_FAILURE,MODEL_LIFE_ID,MODEL_LIFE_VALUE,MODEL_CALLER,
 MODEL_INVOKE_START,MODEL_INVOKE_TUPLE,MODEL_INVOKE_ARGS,MODEL_INVOKE_OWNER,MODEL_INVOKE_POINT,MODEL_INVOKE_LINK};
enum {F_VOLUME=1,F_PAN,F_MUTE,F_SOLO,F_ARM,F_DERIVED_MUTE,F_COLOR,F_NAME};
enum {MODEL_BAD_ROOT=32,MODEL_BAD_VECTOR,MODEL_DUPLICATE_TRACK,MODEL_CONTEXT_UNKNOWN,
 MODEL_LOAD_UNKNOWN,MODEL_OWNER_UNKNOWN,MODEL_ENVELOPE_CHANGED,MODEL_LIFETIME_AMBIGUOUS,MODEL_RETIRED_FULL,MODEL_COMMAND_CONTEXT,MODEL_COMMAND_CAPACITY};
#endif
