/* Bridge-owned motor output admission. Never changes source values or MIDI input. */
#ifndef MPC_MOTOR_FOLLOW_H
#define MPC_MOTOR_FOLLOW_H
#include <stdint.h>
#include <string.h>
#include <stdlib.h>
typedef struct {
 uint32_t key[16],last_tick,quiet_until,hold_until,turns[4];
 unsigned bound,turn_count,sync,target_seen;int last_sent,physical,extreme,direction,target;
} MotorFollow;
typedef struct {MotorFollow motors[9];unsigned enabled;uint32_t barrier;} MotorFollowing;
static void motor_follow_reset(MotorFollowing *f){
 unsigned enabled=f->enabled;memset(f,0,sizeof(*f));f->enabled=enabled;
 for(unsigned i=0;i<9;i++)f->motors[i].physical=f->motors[i].last_sent=-1;
}
static void motor_follow_report(MotorFollow *m,int position,uint32_t now,int accepted_travel){
 if(position<0||position>16383)return;
 if(position!=m->physical&&(m->physical>=0||accepted_travel)){
  m->quiet_until=now>UINT32_MAX-150?UINT32_MAX:now+150;
  /* Observed travel suppresses motor output; it is not a commanded position. */
 }
 m->physical=position;
}
static void motor_follow_target(MotorFollow *m,const uint32_t key[16],int target,uint32_t now){
 if(!m->bound||memcmp(m->key,key,sizeof(m->key))){
  memcpy(m->key,key,sizeof(m->key));m->bound=1;m->sync=1;
  /* Retain observed/emitted position knowledge across the identity change. */
 }
 /* Reversal history belongs to the physical motor, not its current binding.
  * A remap changes target identity without erasing a sustained hold. */
 if(!m->target_seen){m->target_seen=1;m->extreme=target;}else{
  int delta=target-m->extreme;
  if((!m->direction&&abs(delta)>=256)||(m->direction>0&&delta<=-256)||(m->direction<0&&delta>=256)){
   int direction=delta>0?1:-1;
   if(m->direction&&direction!=m->direction){
    unsigned n=0;for(unsigned i=0;i<m->turn_count;i++)if(now>=m->turns[i]&&now-m->turns[i]<=500)m->turns[n++]=m->turns[i];
    if(n==4){memmove(m->turns,m->turns+1,3*sizeof(*m->turns));n=3;}m->turns[n++]=now;m->turn_count=n;
    if(n>=4||now<m->hold_until)m->hold_until=now>UINT32_MAX-250?UINT32_MAX:now+250;
   }
   m->direction=direction;m->extreme=target;
  }else if((m->direction>0&&target>m->extreme)||(m->direction<0&&target<m->extreme))m->extreme=target;
 }
 m->target=target;
}
/* Observe target changes even while output is suspended. Software thresholds
 * are qualification defaults, not claims about the motor's mechanical rating. */
static int motor_follow_due(MotorFollow *m,uint32_t now,int allowed){
 if(!m->bound||!allowed||now<m->quiet_until||now<m->hold_until||now<m->last_tick||now-m->last_tick<10)return -1;
 /* Hardware follows only the latest authoritative target. No interpolated
  * positions or queue of obsolete targets is generated by this policy. */
 return m->sync||m->target!=m->last_sent?m->target:-1;
}
static void motor_follow_sent(MotorFollow *m,int position,uint32_t now){m->last_sent=position;m->last_tick=now;m->physical=-1;m->sync=0;}
#endif
